branch-defaults:
  master:
    environment: flask-env
    group_suffix: null
global:
  application_name: flask
  branch: null
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
aws:elasticbeanstalk:container:python:
    NumProcesses: 6
    NumThreads: 15